apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tea
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - namespace: dev-plaintext
  template:
    metadata:
      name: '{{namespace}}-tea'
    spec:
      project: default
      source:
        repoURL: https://github.com/trevor-dolby-at-ibm-com/ace-demo-gitops.git
        #targetRevision: ignore-secret-values
        targetRevision: HEAD
        path: tea-ace-demo/envs//{{namespace}}
      destination:
        server: https://kubernetes.default.svc
        namespace: tea-{{namespace}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - Validate=false
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - kind: Secret
          group: "*"
          jsonPointers:
            - /data
#            - /data/other-field-that-argocd-should-not-track
          jqPathExpressions:
            - '.data | keys[] | select(. != "field_for_argocd_to_track")'
#            - '.data | keys | map(select(. != "field-for-argocd-to-track"))'
