apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tea
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - namespace: dev-secure
      - namespace: dev-plaintext
      - namespace: qa
  template:
    metadata:
      name: '{{namespace}}-tea'
    spec:
      project: default
      source:
        repoURL: https://github.com/trevor-dolby-at-ibm-com/ace-demo-gitops.git
        targetRevision: HEAD
        path: tea-ace-demo/envs//{{namespace}}
      destination:
        server: https://kubernetes.default.svc
        namespace: tea-{{namespace}}
