apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-ace-demo
spec:
  template:
    spec:
      containers:
      - name: tea-ace-demo
        env:
        - name: ENV
          value: "qa"
        - name: LICENSE
          value: "accept"
