apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: image-placeholder
    newName: tdolby/experimental
    #newTag: tea-github-action-crane-20241122004459-050e41a
    newTag: tea-github-action-crane-20241122004459-050e42d
components:
  - ../../variants/secure
patchesStrategicMerge:
  - deployment.yaml
  #- version.yaml
