---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: teajdbc-jlkm9
  namespace: demo-qa
spec:
  encryptedData:
    configuration: AgCYMtFy7UtO0nV76bgp5Bii+NHSvXEF66BX5eIpCcu7u8HB6QKPSPJsh6rh1sj4FtK7wmcmREj+WRJ1qdEsy7pLklSPLH2M6Es8x2Au/1QkylsDl0OU5hkJSvGLyS+BxwGKQbZNgf6jzYgK86MF314rCceuUKw36y6rKXfSuLBPZeo5Tqz8km4H+yGGBdSODQN/oDKfiAcaIfh71/knqPHuHbC50SLXWya67HxU4i/ViIMd3sOz/7AnHPwVRMU2E5KEmVZWr4wWNOjt8ZW76h66g5lXvBv74g6zQVFwFekk7U+XALrhA8TPcjZcQHrQWmpFFATmtHZ8S5EgeVBN7CIIz6k607QMaSNHGvtcKKo3QImSubUF6kZYYlb0FrE1zRkPAsNOahMznGmTeXXyzFom3CISvRjW9W/B6sfqit9vzIk+2UaQtwY53vZ9qo6/Tbb7wJccVWFV3/KZV02mWpcz5cKnUIum5/CtX+9ix02HjUNvBjEBvZ5erGVgqWcGcCoWOVEYhgMccPd4tBHvxL8w8Rm9mhyeo6wEmlMsBEkxpIgEz2PkuCyjc08rRiXPlSEs20uZUVRorLyIS0TMrMNhBkAUL3dzJr5gyvkv8qQ46pYD9hHCdBpkqq2koIWDsvi20uDhnKhQoGfKih0B/5I/ojd0D5IgC3IsuX+F1/R9ZOqq9snwVVGiJ2KaF72ZRE2wK/KjBffIO4Nbz/X7QEucf7xSoBgesYE7LtUq0C923qzjrg==
  template:
    metadata:
      labels:
        app.kubernetes.io/component: configuration
        app.kubernetes.io/instance: teajdbc
        app.kubernetes.io/managed-by: ibm-appconnect
        app.kubernetes.io/name: teajdbc
        appconnect.ibm.com/kind: Configuration
        backup.appconnect.ibm.com/component: configuration
        bcdr-candidate: t
        release: teajdbc
      name: teajdbc-jlkm9
      namespace: demo-qa
    type: Opaque
