apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-application-set
  namespace: openshift-gitops
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # list generator, 'child' #1
          # This could be a clusterDecisionResource
          - list:
              elements:
                - name: democluster
                  server: https://kubernetes.default.svc
          # matrix 'child' generator #2
          - matrix:
              generators:
                # git generator, 'grandchild' #1
                - git:
                    repoURL: https://github.com/trevor-dolby-at-ibm-com/ace-demo-gitops.git
                    revision: tea-ir-plus-tcpip
                    directories:
                      - path: '*-ace-demo'
                # list generator, 'grandchild' #2
                - list:
                    elements:
                      - namespace: dev
                        fakeserver: 'https://api.test1.cluster:6443'
                      - namespace: qa
                        fakeserver: 'https://api.test2.cluster:6443'
  goTemplate: true
  template:
    metadata:
      name: '{{.name}}-{{.path.basename}}-{{.namespace}}'
    spec:
      project: default
      source:
        kustomize:
          patches:
            - patch: |-
                - op: add 
                  path: /spec/template/spec/containers/0/env/0/name
                  value: 'CLUSTER_APPS_DNS'
                - op: add # Likely to be of the form https://api.cluster.host:6443
                  path: /spec/template/spec/containers/0/env/0/value
                  value: '{{- $url := urlParse .fakeserver -}}something-else-{{ replace "api." "apps." $url.hostname }}'
              target:
                kind: Deployment
        repoURL: https://github.com/trevor-dolby-at-ibm-com/ace-demo-gitops.git
        targetRevision: tea-ir-plus-tcpip
        path: '{{.path.path}}/envs//{{.namespace}}'
      destination:
        server: '{{.server}}'
        namespace: demo-{{.namespace}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - Validate=false
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
      ignoreDifferences:
        - group: appconnect.ibm.com
          kind: IntegrationRuntime
          jqPathExpressions:
            - '.spec.configurations[] | select(endswith("-adminssl"))'
