kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: separateclaimsqm-ibm-mq-recovery-logs
  labels:
    app.kubernetes.io/component: integration
    app.kubernetes.io/instance: separateclaimsqm
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: ibm-mq
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: separateclaimsqm-recovery-logs-pv
  volumeMode: Filesystem
  storageClassName: no-provisioner-sc
