apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-ace-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: tea-ace-demo
  template:
    metadata:
      labels:
        app: tea-ace-demo
    spec:
      volumes:
      - name: secret-volume-2
        secret:
          secretName: jdbc-secret
      containers:
      - image: placeholder
        name: tea-ace-demo
        ports:
        - containerPort: 7800
        volumeMounts:
        - name: secret-volume-2
          mountPath: /var/run/secrets/jdbc
