kind: Secret
apiVersion: v1
metadata:
  name: first-secret
  annotations:
    test-version: '2'
data:
  field-for-argocd-to-track: QkxVREI=
  field-that-argocd-should-not-track: bWludXNvbmUK
  other-field-that-argocd-should-not-track: emVybwo=
type: Opaque
