apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  annotations:
    appconnect.ibm.com/updating: 'false'
  name: tea-ace-demo
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
spec:
  barURL: []
  configurations:
    - teajdbc
    - teajdbc-policy
    - default-policy
  flowType:
    toolkitFlow: true
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: AppConnectEnterpriseNonProductionFREE
  logFormat: basic
  replicas: 1
  template:
    spec:
      containers:
        - image:  >-
            image-placeholder
          name: runtime
          resources:
            requests:
              cpu: 300m
              memory: 368Mi
  version: 12.0.12-r22
