kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tea-ace-demo-route
spec:
  to:
    kind: Service
    name: tea-ace-demo
    weight: 100
  port:
    targetPort: 7800
  wildcardPolicy: None
