apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: image-placeholder
    newName: docker.io/tdolby/experimental
    newTag: tea-github-action-crane-20260424190513-398448d
