apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: image-placeholder
    newName: docker.io/tdolby/experimental
    newTag: ace-tcpip-flow-experiments-20260424173147-e6a7b5d4

