apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpip-ace-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: tcpip-ace-demo
  template:
    metadata:
      labels:
        app: tcpip-ace-demo
    spec:
      containers:
      - image: >-
          image-placeholder
        name: tcpip-ace-demo
        env:
        - name: CLUSTER_APPS_DNS
          value: "should.be.set.by.application.set"
        - name: ENV
          value: "dev"
        - name: TESTVAR
          value: "somevalue"
        - name: LICENSE
          value: "accept"
        ports:
        - containerPort: 7800
        - containerPort: 12345
