---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: teajdbc-jlkm9
  namespace: demo-dev
spec:
  encryptedData:
    configuration: AgBssyWq1GvwJj9oXNJnPhAX1RvCdQyQWbNNnSvQ41EcfsC1kiAwtJZ3eI6X9hAy4bO3j9fPZvPM5IoiFb9JHQ2ps4qiqzuif3WN5DukC87BUagW5SsobOE3lgRGK0obnlPT7DZx+gUhr6auLGIfSMQ2Mn29Nvu8MRsmr1BHNaI2Ew2sfe+CD4ugMw3dfyeQabrXKHUqgWMy/hDtO8Iq9cgF4wQzIH+wyCpnNtIHNhoesxuT88NhgnbyqaIFqyhPRDI3IqGMU5CiYZLIj6xouLVf0Js7KkCLS3dSwdOHxhdywoticZ5FYlOjuMZbaSiB4BysqVkjZOuvae6Yreg24qOuBho7PdNV97XJHMi5J/EdPMOt4fkjme1VD/OA4F53dDrYpqPLX31hMHe75r2UXhcKdHKbfyDgC3MLVKz0FAySE99GOGhmtW2Ek28Nl+HMHt9GNcWcnry1HS0afBCsmIow37+RCdZV5OMZh1Pakr0LPl19JF6AoCjVKyFfOZCAK5K7q6Q47cihAzyG7bU2N61HUWAxYSbgcanBe0CstTqGw37YMvNV2dUT+qWBCbKT8CwcQlRuo5rLGvuq/2gyaG8l1uEgWKadDsRr9fXtxhfyvwyTPp9DwFsTOkeK/nEgJOrWR0SyrGMmRd19G8MsvjD/tZBg4mhyVX19GJXJo/LgtglmYspAcB043vbTpvgqozh1Kbo+kc4INQUPGLRM6vVJWU658cEqpnhReJLeBXoBnfF+3Q==
  template:
    metadata:
      labels:
        app.kubernetes.io/component: configuration
        app.kubernetes.io/instance: teajdbc
        app.kubernetes.io/managed-by: ibm-appconnect
        app.kubernetes.io/name: teajdbc
        appconnect.ibm.com/kind: Configuration
        backup.appconnect.ibm.com/component: configuration
        bcdr-candidate: t
        release: teajdbc
      name: teajdbc-jlkm9
      namespace: demo-dev
    type: Opaque
