---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: teajdbc-jlkm9
spec:
  encryptedData:
    configuration: AgBEfjuLNFg1nP3UbBIsHJ2o6/tnz9XVQGf5th09m4dXRxUzvr9rx8rE7dQRix9cg2Q96ylHOxA/WMoMpoUlRFHFH95RoxgtF0MjaGk8HimDxEHAO5a82dUv36uYx1HvTgSzgMBluuBevHKUxJHGGY/UBoQQJ1/XLerJV0tHAQr/km/SWylVJb9tCGFwARBpkey+xa6EBkfDGu/UzzblNRLk2G7N7W6BjyUYbI/pLWgfO0GXkzEwTX4cmyWmA2qvrDOrwZOBSX1OmkTRXuTzcllzWD6ua6YkxVNciw0XaxSYfyUicsQ+9uK5s+ZQcTE1bLEdj36uiTE8wsIaOv/y7JMpUKw8zFfmvFwPyPZtHJ40sXs+qkNmnCfn4RS7xRYCeH0yFY0FymhffvJFXXpSC+Y36BMTVCPtKJsrANa21dd+hYLHTyps6yZPwJhTd8C+bktEtasxIIviHljSKU4N/lnxDxtqG3rVdyqc847T1OIuYV19X027HSBKtXtuBLJhrtn2yNvunFJElvcFcZ0A4j+igOSbf2AIMR1dqygzaO1cp5o8mTa5ryaKpyeK/B+nbYH9YT9N2+vlwkhDdtbWf7TMvbl9Z/T3AMpiMiKhqORwbpt8CZGJLkLcSngcWjzpQm5/g63rEmpeqa8tIr98HkLE9yru3fHrXbMU/4B3hzNiP7yMQ8OZvUDwWTg7Z8jesM6Tu8g8C/th9FRxLyRhSzH1Qa1I6fcLyYwgbBHMM2ct5C8gnw==
  template:
    metadata:
      labels:
        app.kubernetes.io/component: configuration
        app.kubernetes.io/instance: teajdbc
        app.kubernetes.io/managed-by: ibm-appconnect
        app.kubernetes.io/name: teajdbc
        appconnect.ibm.com/kind: Configuration
        backup.appconnect.ibm.com/component: configuration
        bcdr-candidate: t
        release: teajdbc
      name: teajdbc-jlkm9
      namespace: demo-dev
    type: Opaque
