name: Create draft PR for dev-to-qa promotion of images

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]
    paths:
      # This will trigger on any file with "dev" in the path at any level
      # and means we won't get invoked for all file changes. Filtering is
      # still needed in the scripts to make sure an image tag has actually 
      # changed, but the filter stops actions being runn too often when 
      # there's nothing to do for the dev environment.
      #
      # See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#using-filters
      # for more details.
      - '**dev**.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '20'
          
      - name: Promote dev-plaintext to QA
        shell: bash
        run: |
          echo "Environment"
          env | sort
          echo ${GITHUB_EVENT_PATH} contents
          cat ${GITHUB_EVENT_PATH}
          echo "########################################################################"
          echo "# Calling scripts/01-do-env-promotion.sh"
          echo "#   dev-plaintext qa <GITOPS_GH_TOKEN>"
          echo "########################################################################"
          scripts/01-do-env-promotion.sh dev-plaintext qa ${{ secrets.GITOPS_GH_TOKEN }}
