name: Print Env

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '20'
          
      - name: Print environment
        shell: bash
        run: |
          echo "Environment"
          env | sort
          echo ${GITHUB_EVENT_PATH} contents
          cat ${GITHUB_EVENT_PATH}
