name: Print Env

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
          
      - name: Print environment
        shell: bash
        run: |
          echo "Environment"
          env | sort
          echo ${GITHUB_EVENT_PATH} contents
          cat ${GITHUB_EVENT_PATH}
          echo "Calling scan-commits-for-image-changes.sh"
          scripts/scan-commits-for-image-changes.sh dev-plaintext qa ${GITHUB_EVENT_PATH}
          echo "Calling push-changes-to-new-branch.sh"
          scripts/push-changes-to-new-branch.sh qa
          
